#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Console\GenerateCommand;
use Console\GenerateConversation;
use Console\GenerateMiddleware;
use Symfony\Component\Console\Application;
 
$app = new Application();
$app->add(new GenerateCommand());
$app->add(new GenerateConversation());
$app->add(new GenerateMiddleware());
$app->run();